# EM PRODUÇÃO ESTE ARQUIVO É MONTADO NA PIPELINE E TODA ALTERAÇÃO REALIZADA DEVE SER INFORMADA AO DEVOPS PARA ATUALIZAR A VARIÁVEL "CONSTANTS_PROD" NO GITLAB

# AWS
AWS_REGION = "us-east-1"
AWS_ACCOUNT_ID = "628690981918"
AWS_EVENT_BUS_NAME = "cts-eventbus"
AWS_SECRETS_NAME = "cts-secrets"  # Secret Manager
AWS_DELIVERY_STREAM = "cts-log-dev"
AWS_WEBHOOK_QUEUE_NAME = "centerpag-webhook-dev-queue"
AWS_SNS_ALERT_TOPIC = "cts-alerts"

# ENV
APP_ENV = "local"
DEVELOPMENT_ENVIRONMENTS = ["local", "dev"]

# DB
DB_TABLE_SCHEMA = "cts"
DB_PORT = 31110

# TRANSACTION RETRY
TIMES_TRANSACTION_RETRY = 5
SECONDS_INTERVAL_TRANSACTION_RETRY = 0.5

# REDIS
REDIS_EXPIRATION_TIME_SECONDS = 3600  # 1 hora
REDIS_HOSTNAME = "master.centerpag-dev.byhhsx.use1.cache.amazonaws.com"
REDIS_PORT = 6379
REDIS_PASSWORD = "8Papp54UxTbYVhXA"

# DEFAULT RESPONSES CODE
DEFAULT_SUCCESS_MESSAGE_CODE = "ADQ0"
DEFAULT_ERROR_MESSAGE_CODE = "ADQ6"
DEFAULT_PENDING_TRANSACTION_CODE = "ADQ28"

# CRYPTHOGRAPHY SALT
CRYPTHOGRAPHY_SALT = "6a38ffeddb338c86b2a3"

# INSTALLMENTS MERCADOPAGO
URL_INSTALLMENTS_MERCADOPAGO = (
    "https://api.mercadopago.com/v1/payment_methods/installments"
)

# CAPTURE METHODS
CAPTURE_METHOD_SYNCHRONOUS = "SYNCHRONOUS"